server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#zuul:
#  routes:
#    user-service: /user-service/**
#     path: /user-service/**
#     serviceId: user-service
#     url: http://localhost:8082
spring:
  application:
    name: gatway
zuul:
  prefix: /api
  routes:
    user-service: /user/**
#    user-service:
#      path: /user/**
#      serviceId: user-service
#      strip-prefix: false
#  strip-prefix: false
  ignored-services:
    - consumer-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 0 #不重试

